### PR TITLE
Add code to remove legacy `validation_marker` file that created by etcd-custom-image on the filesystem

### LINKED ISSUE #37: Remove legacy `validation_marker` file
**Feature (What you would like to be added):**
Clean up legacy `validation_marker` file created by etcd-custom-image

**Motivation (Why is this needed?):**
Don't store any files with wide permissions, and the `validation_marker` file was created by etcd-custom-image with `0644` mode.

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area compliance security
/kind task

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #37

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by ishan16696** [comment]
Hey Shreyas,
As I can see the code, there is already code present to clean-up the exit code after etcd successfully starts.
https://github.com/gardener/etcd-wrapper/blob/d3b0f822b9e81d5a9450f6500b2f902df5b58cd7/internal/app/app.go#L96-L100

May be what you have seen could be some edge cases in which etcd-wrapper failed to remove old `validation_marker`.
Can you make changes in same file like this: 

```go
	// Delete legacy validation marker after etcd starts successfully
        // TODO: To be removed in next release
	if err = bootstrap.CleanupExitCode(types.LegacyValidationMarkerFilePath); err != nil {
		a.logger.Warn("failed to clean-up last captured exit code", zap.Error(err))
	}
```

**Comment by shreyas-s-rao** [comment]
@ishan16696 that code cleans up the new `exit_code` file, but not `validation_marker`. Seems to be a mistake in the comment on line 96 that says `Delete validation marker after etcd starts successfully` instead of saying `Delete exit code file after etcd starts successfully`.

So deletion of `validation_marker` file is necessary, via this PR. I'll fix the old comment as well.

**Comment by ishan16696** [comment]
> that code cleans up the new exit_code file, but not validation_marker

`validation_marker` is just a file name, you can call it either `exit_code` file or `validation_marker` file but both of them captures the exit code of etcd. It just file path has changed.
So, my point was there is already a code in place which removes the file where exit code is captured, and may be due to some edge case some in which etcd-wrapper failed to remove old old path of exit code file (i.e validation_marker file).

I'm saying can we reuse the same func and just pass the old path of exit code file (i.e validation_marker file).
```go
	// Delete legacy validation marker after etcd starts successfully
        // TODO: To be removed in next release
	if err = bootstrap.CleanupExitCode(....); err != nil {
		a.logger.Warn("failed to clean-up legacy exit code file", zap.Error(err))
	}
```

**Comment by shreyas-s-rao** [comment]
@ishan16696 not really. etcd-wrapper is designed to delete the `exit_code` file after the etcd process starts, so that an abrupt kill of the etcd-wrapper container does not lead to a wrong validation mode upon restart. Ok, I now understand that you want to re-use the CleanupExitCode() function for doing this, correct? My bad for not reading the previous comment correctly, sorry 😅.

I've pushed the change as requested. PTAL.

**Review by ishan16696 — APPROVED** [review]
Thanks @shreyas-s-rao  for PR.
LGTM!!

**Pull request merged**
